convenient_tasks/urls.py
import django.contrib.auth.views as auth

from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from problems.views import task_search, task_detail, pools, pool_pdf, index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth.LoginView.as_view(template_name='problems/pages/login.html'), name='login'),
    url(r'^logout/$', auth.LogoutView.as_view(next_page='/login'), name='logout'),
    url(r'^tasks/$', task_search),
    url(r'^task/(?P<pk>\d+)/$', task_detail),
    url(r'^pools/$', pools),
    url(r'^pools/pdf/$', pool_pdf),
    url(r'^$', index)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problems/models.py
import os

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.safestring import mark_safe
from tagging.fields import TagField
from tagging.models import Tag


class User(AbstractUser):
    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        if not self.taskpool_set.filter(name='Избранное').exists():
            TaskPool.objects.create(
                name='Избранное',
                user=self
            )
        dir_name = os.path.join(settings.TEMPORARY_FOLDER, settings.USERS_FILES, str(self.username))
        if not os.path.exists(dir_name):
            os.mkdir(dir_name)


class GradeManager(models.Manager):
    def range(self, min_grade=1, max_grade=11):
        return self.filter(grade__gte=min_grade).filter(grade__lte=max_grade).all()


class Grade(models.Model):
    """
    Модель для класса
    """
    PATTERN = '{} класс'

    grade = models.SmallIntegerField(unique=True, verbose_name='Класс')
    tag = models.OneToOneField(Tag, on_delete=models.CASCADE)

    objects = GradeManager()

    def __str__(self):
        return str(self.PATTERN.format(self.grade))

    class Meta:
        ordering = ['grade']


class AbstractSection(models.Model):
    """
    Модель раздела задач
    (как основного раздела (физика/математика)), так и побочных
    """
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    tag = models.OneToOneField(Tag, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Section(AbstractSection):
    pass


class Subsection(AbstractSection):
    main_section = models.ForeignKey(Section, on_delete=models.CASCADE)


class Task(models.Model):
    """
    Модель для задачи
    """
    tags = TagField(verbose_name='Теги')

    section = models.ForeignKey(Section, related_name='section', verbose_name='Раздел', on_delete=models.CASCADE)  # основной раздел
    subsection = models.ForeignKey(Subsection, related_name='subsection', verbose_name='Подраздел', on_delete=models.CASCADE)  # подраздел

    grades = models.ManyToManyField(Grade, blank=True, verbose_name='Классы')  # классы для данной задачи

    tex_used = models.BooleanField(default=False, verbose_name='TeX')

    def __str__(self):
        return f'Задача {str(self.pk)}'

    def name(self):
        return str(self)

    name.short_description = 'Task name'
    name.admin_order_field = 'pk'

    def has_tip(self):
        return any(section.is_tip for section in self.tasksection_set.all())

    has_tip.boolean = True
    has_tip.short_description = 'Tip'

    def has_solution(self):
        return any(section.is_solution for section in self.tasksection_set.all())

    has_solution.boolean = True
    has_solution.short_description = 'Solution'

    def has_answer(self):
        return any(section.is_answer for section in self.tasksection_set.all())

    has_answer.boolean = True
    has_answer.short_description = 'Answer'


class TaskSection(models.Model):
    """
    Модель для части задачи -- условия, подсказки, решения или ответа
    содержит в себе текст и 0 или больше картинок
    """
    CONDITION = '1'
    TIP = '2'
    SOLUTION = '3'
    ANSWER = '4'

    TYPOS = {
        CONDITION: 'Условие',
        TIP: 'Подсказка',
        SOLUTION: 'Решение',
        ANSWER: 'Ответ'
    }

    text = models.TextField(default='', verbose_name='Текст')
    type = models.CharField(max_length=1, choices=TYPOS.items(), verbose_name='Тип')
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.TYPOS[self.type]} для "{self.task}"'

    def is_condition(self):
        return self.type == self.CONDITION

    def is_tip(self):
        return self.type == self.TIP

    def is_solution(self):
        return self.type == self.SOLUTION

    def is_answer(self):
        return self.type == self.ANSWER

    def get_name(self):
        return self.TYPOS[self.type]


class Image(models.Model):
    """
    Модель для иллюстрации к части задачи
    """
    image = models.ImageField(null=True)  # сама картинка
    number = models.IntegerField(verbose_name='Номер')  # ее номер в задаче
    section = models.ForeignKey(TaskSection, on_delete=models.CASCADE)  # ссылка на задачу

    def image_tag(self):
        return mark_safe(f'<img {self.tag_params()} '
                         f'alt="рис. {self.number}"/>')

    def tag_params(self):
        return f'src={self.image.url} width={self.image.width} height={self.image.height}'

    image_tag.short_description = 'Image'

    def __str__(self):
        return f'Рис. {self.number} of "{self.section}"'


class TaskSource(models.Model):
    name = models.CharField(max_length=100, null=True, verbose_name='Имя')  # название источника
    url = models.URLField(null=True)  # ссылка на источник
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Автор', on_delete=models.CASCADE)  # ссылка на автора
    source = models.OneToOneField(Task, on_delete=models.CASCADE)  # ссылка на задачу

    def __str__(self):
        return f'Источник для "{self.source}"'


class TaskPool(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(default='')
    tasks = models.ManyToManyField(Task)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.name}" of user {self.user}'

problems/forms.py
from django import forms
from problems.templatetags.problems_extras import convert_to_mathml


class EditableTexTextarea(forms.Textarea):
    template_name = 'form_views/tex_textarea.html'

    def render(self, name, value, attrs=None, renderer=None):
        attrs['math'] = convert_to_mathml(value)
        return super().render(name, value, attrs, renderer)

problems/views.py
import pdfkit

from django.contrib.auth.views import redirect_to_login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string

from problems.models import Task, Section, Subsection, User, TaskPool


def index(request):
    return HttpResponseRedirect(redirect_to='/tasks')


def task_detail(request, pk):
    if not request.user.is_authenticated:
        return redirect_to_login(request.path)
    return render(request, 'problems/pages/task.html', {
        'task': Task.objects.get(pk=pk),
        'user': request.user
    })


def task_search(request):
    if not request.user.is_authenticated:
        return redirect_to_login('/tasks')
    return render(request, 'problems/pages/tasks_search.html', {
        'sections': Section.objects.all(),
        'subsections': Subsection.objects.all(),
        'user': request.user
    })


def pools(request):
    if not request.user.is_authenticated:
        return redirect_to_login('/pools')
    return render(request, 'problems/pages/pools.html', {
        'user': request.user
    })


def pool_pdf(request):
    pool_pk = request.GET['pk']
    pool = TaskPool.objects.get(pk=pool_pk)
    pdf = generate_pdf('problems/pdf/pool.html', {'pool': pool})
    return HttpResponse(pdf, content_type='application/pdf')


def generate_pdf(template_name, context):
    html = render_to_string(template_name, context)
    pdf = pdfkit.from_string(html, False)
    return pdf

problems/templates/form_views/tex_textarea.html
<div class="col-md-5">
    <p>
        {% if widget.value %}
            {{ widget.attrs.math | safe }}
        {% endif %}
    </p>
</div>

<div class="col-md-5">
    <textarea name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% if widget.value %}{{ widget.value }}{% endif %}</textarea>
</div>

problems/templates/problems/elements/no_task_placeholder.html
<div id="task-detail">
    <h4>Задач по данному запросу не найдено</h4>
</div>

problems/templates/problems/elements/pool_button.html
<div>
    <button type="button" class="btn btn-default pool-button" pk="{{ pool.pk }}" {% if pool.name == 'Избранное' %}
    id="pool-favorite"
    {% endif %}>
        <h5>{{ pool.name }}</h5>
    </button>
    <a class="btn btn-default pool-pdf" href="pdf?pk={{ pool.pk }}" target="_blank"><span class="glyphicon glyphicon-floppy-save"></span></a>
</div>

problems/templates/problems/elements/pool_list_element.html
<li id="pool-{{ pool.pk }}"><a class="pool-list-dropdown-button" pool_pk="{{ pool.pk }}" href="#">
    {{ pool.name }}
    {% if task in pool.tasks.all %}
        <span class="glyphicon glyphicon-ok"></span>
    {% endif %}
</a></li>

problems/templates/problems/elements/task_button.html
<button id="task-button-{{ task.pk }}" type="button" class="btn btn-default task-button" pk="{{ task.pk }}">
    <h5>{{ task.name }}</h5>
{#    <div class="btn-group btn-group-xs">#}
{#        {% for tag in tags %}#}
{#            <button class="btn btn-default">{{ tag }}</button>#}
{#        {% endfor %}#}
{#    </div>#}
</button>

problems/templates/problems/elements/task_detail.html
<div id="task-detail" task_pk="{{ task.pk }}">
<div class="row">
    <div class="col-md-11 col-lg-11">
        {% load problems_extras %}
        {% for section in task.tasksection_set.all %}
            <h3>{{ section.get_name }}</h3>
            <p>{{ section.text|math }}</p>
            {% for image in section.image_set.all %}
                <figure>
                    <img class="img-responsive" {{ image.tag_params }}/>
                    <figcaption>Рис. {{ image.number }}</figcaption>
                </figure>
            {% endfor %}
        {% endfor %}

        <h4><b>Раздел</b></h4>
        <p>{{ task.section }}</p>

        <h4><b>Подраздел</b></h4>
        <p>{{ task.subsection }}</p>

        <h4><b>Классы</b></h4>
        <ul>
            {% for grade in task.grades.all %}
                <li>{{ grade }}</li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-md-1 col-lg-1">
        {% block buttons %}
        {% endblock %}
    </div>
</div>
</div>

problems/templates/problems/elements/task_detail_default_panel.html
<div id="task-detail"></div>

problems/templates/problems/elements/task_detail_pools.html
{% extends 'problems/elements/task_detail.html' %}

{% block buttons %}
    <button id="remove_task_button" type="button" class="btn btn-default"><span class="glyphicon glyphicon-trash"></span></button>
{% endblock %}

problems/templates/problems/elements/task_detail_search.html
{% extends 'problems/elements/task_detail.html' %}

{% block buttons %}
    <div class="input-group">
        <div class="input-group-btn">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Добавить в набор<span class="caret"></span></button>
            <ul class="dropdown-menu" id="pool-list-dropdown">
                {% for pool in user.taskpool_set.all %}
                    {% include 'problems/elements/pool_list_element.html' %}
                {% endfor %}
                <li class="divider" id="pool-divider"></li>
                <li>
                    <input class="form-control" id="new-pool-dropdown-button" placeholder="Новый набор">
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

problems/templates/problems/elements/tasks_list_element.html
<button id="task-button-{{ task.pk }}" type="button" class="btn btn-default task-button" pk="{{ task.pk }}">
    <h5>{{ task.task_name }}</h5>
{#    <div class="btn-group btn-group-xs">#}
{#        {% for tag in tags %}#}
{#            <button class="btn btn-default">{{ tag }}</button>#}
{#        {% endfor %}#}
{#    </div>#}
</button>

problems/templates/problems/elements/tasks_list_panel.html
<div id="tasks-list-group" style="overflow: auto; max-height: 700px;">
    <div id="tasks-list" class="btn-group-vertical"></div>
    <button id="give-me-more" type="button" class="btn">Больше задач</button>
</div>

problems/templates/problems/login.html
{% extends 'problems/base.html' %}

{% block no_bar_content %}
    <div class="container">
        <div class="row">
            <h2>Login</h2>
            <form method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input name="username" autofocus="" maxlength="254" required="" id="id_username" placeholder="login" type="text">
                </div>
                <div class="input-group">
                    <input name="password" required="" id="id_password" placeholder="password" type="password">
                </div>
                <button class="btn btn-default" type="submit">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

problems/templates/problems/pages/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {% endblock %}
    <title>{% block title %}Convenient tasks{% endblock %}</title>
</head>
<body>
{% block no_bar_content %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Convenient tasks</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/tasks/">Tasks</a></li>
                    {% block extra_nav_buttons_left %} {% endblock %}
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input id="search-input" type="number" class="form-control" placeholder="Go to task"
                               {% if task %}
                                    value="{{ task.pk }}"
                               {% else %}
                                    value="1"
                               {% endif %}
                        >
                    </div>
                    <button id="search-button" type="button" class="btn btn-default">Искать</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% block extra_nav_buttons_right %} {% endblock %}
                    {% if user %}
                        <li><a><b>{{ user.username }}</b></a></li>
                        <li><a href="/pools/">Мои наборы</a></li>
                        <li><a href="/logout/">Log out</a> </li>
                    {% else %}
                        <li><a href="/signup/">Sign up</a></li>
                        <li><a href="/login/">Log in</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
            <div class="row">
                <div class="col-md-2 col-lg-2">{% block left_panel %}{% endblock %}</div>
                <div class="col-md-2 col-lg-2">{% block center_panel %}{% endblock %}</div>
                <div class="col-md-8 col-lg-8">{% block details_panel %}{% endblock %}</div>
            </div>
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src={% static "js/lib/bootstrap.js" %}></script>
    <script src="{% static 'js/base_main.bundle.js' %}"></script>
{% endblock %}
</body>

problems/templates/problems/pages/login.html
{% extends 'problems/pages/base.html' %}

{% block no_bar_content %}
    <div class="container">
        <div class="row">
            <h2>Login</h2>
            <form method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input name="username" autofocus="" maxlength="254" required="" id="id_username" placeholder="login" type="text">
                </div>
                <div class="input-group">
                    <input name="password" required="" id="id_password" placeholder="password" type="password">
                </div>
                <button class="btn btn-default" type="submit">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

problems/templates/problems/pages/pools.html
{% extends 'problems/pages/base.html' %}

{% block left_panel %}
    <div id="pools-list" style="overflow: auto; max-height: 700px;" class="btn-group-vertical">
    {% for pool in user.taskpool_set.all %}
        {% include 'problems/elements/pool_button.html' %}
    {% endfor %}
    </div>
{% endblock %}

{% block center_panel %}
    {% include 'problems/elements/tasks_list_panel.html' %}
{% endblock %}

{% block details_panel %}
    {% include 'problems/elements/task_detail_default_panel.html' %}
{% endblock %}}

{% block scripts %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'js/pools_main.bundle.js' %}"></script>
{% endblock %}

problems/templates/problems/pages/task.html
{% extends 'problems/pages/base.html' %}

{% block content %}
    {% include 'problems/elements/task_detail_search.html' %}
{% endblock %}

problems/templates/problems/pages/tasks_search.html
{% extends 'problems/pages/base.html' %}

{% block left_panel %}
    <div id='sections' class="input-group">
        <div class="input-group-btn">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">{{ sections.first }}<span class="caret"></span></button>
            <ul class="dropdown-menu">
                {% for section in sections %}
                    <li><a href="#">{{ section }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div id='subsections' class="input-group">
        <div class="input-group-btn">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">{{ subsections.first }}<span class="caret"></span></button>
            <ul class="dropdown-menu">
                {% for section in subsections %}
                    <li><a href="#">{{ section }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div id="grade-slider"></div>
{% endblock %}

{% block center_panel %}
    {% include 'problems/elements/tasks_list_panel.html' %}
{% endblock %}

{% block details_panel %}
    {% include 'problems/elements/task_detail_default_panel.html' %}
{% endblock %}

{% block css %}
    {{ block.super }}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/grade_slider.css' %}">
{% endblock %}

{% block scripts %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'js/task_search_main.bundle.js' %}"></script>
{% endblock %}

problems/templates/problems/pdf/pool.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ pool.name }}</title>
</head>
<body>
    <h2>{{ pool.name }}</h2>
    {% for task in pool.tasks.all %}
        {% include 'problems/pdf/task.html' %}
    {% endfor %}
</body>
</html>

problems/templates/problems/pdf/task.html
<h2>{{ task.name }}</h2>
{% load problems_extras %}
{% for section in task.tasksection_set.all %}
    <h3>{{ section.get_name }}</h3>
    <p>{{ section.text|math }}</p>
    {% for image in section.image_set.all %}
        <figure>
            <img class="img-responsive" {{ image.tag_params }}/>
            <figcaption>Рис. {{ image.number }}</figcaption>
        </figure>
    {% endfor %}
{% endfor %}

problems/templates/problems/pools.html
{% extends 'problems/base.html' %}

{% block left_panel %}
    <div id="pools-list" style="overflow: auto; max-height: 700px;" class="btn-group-vertical">
    {% for pool in user.taskpool_set.all %}
        {% include 'problems/elements/pool_button.html' %}
    {% endfor %}
    </div>
{% endblock %}

{% block center_panel %}
    {% include 'problems/elements/tasks_list_panel.html' %}
{% endblock %}

{% block details_panel %}
    {% include 'problems/elements/task_detail_default_panel.html' %}
{% endblock %}}

{% block scripts %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'js/pools_main.bundle.js' %}"></script>
{% endblock %}

problems/templates/problems/task.html
{% extends 'problems/base.html' %}

{% block content %}
    {% include 'problems/elements/task_detail.html' %}
{% endblock %}

problems/templates/problems/tasks_search.html
{% extends 'problems/base.html' %}

{% block left_panel %}
    <div id='sections' class="input-group">
        <div class="input-group-btn">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">{{ sections.first }}<span class="caret"></span></button>
            <ul class="dropdown-menu">
                {% for section in sections %}
                    <li><a href="#">{{ section }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div id='subsections' class="input-group">
        <div class="input-group-btn">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">{{ subsections.first }}<span class="caret"></span></button>
            <ul class="dropdown-menu">
                {% for section in subsections %}
                    <li><a href="#">{{ section }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div id="grade-slider"></div>
{% endblock %}

{% block center_panel %}
    {% include 'problems/elements/tasks_list_panel.html' %}
{% endblock %}

{% block details_panel %}
    {% include 'problems/elements/task_detail_default_panel.html' %}
{% endblock %}

{% block css %}
    {{ block.super }}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/grade_slider.css' %}">
{% endblock %}

{% block scripts %}
    {{ block.super }}
    {% load static %}
    <script src="{% static 'js/task_search_main.bundle.js' %}"></script>
{% endblock %}